# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b49d8e3ba2dc7520715eaf7a6f7e03f8a34984164e23c1054a3eb5aeb723e75e853fc9b53b8a81dd9818c790ee0dc6e63cf8bac8bac343b367941c4c712cbda

test:
  secret_key_base: a87152013a58087578996c5d123bbbb8936aa832d87e897a7084519213ed953cb017548f7e980e94553ad25e2acf243366a3ebf15d26dce690d35166f7f91e7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
